Enable to set timezone Calendar for writing and reading timestamp data
oliverselinger/failsafe-executor pull request #58
Opened 2023-11-13 15:02 UTC by hokorn

2023-11-14 07:29 UTC, cinemast requested changes

2023-11-14 07:29 UTC, cinemast commented on src/main/java/os/failsafe/executor/FailsafeExecutor.java
> +import java.util.*;
please revert and avoid `*` imports

2023-11-14 07:29 UTC, cinemast commented on src/main/java/os/failsafe/executor/TaskRepository.java
> +import java.sql.*;
please revert and avoid `*` imports

2023-11-14 07:29 UTC, cinemast commented on src/main/java/os/failsafe/executor/TaskRepository.java
> +import java.util.*;
please revert and avoid `*` imports

2023-11-14 07:29 UTC, cinemast commented on src/main/java/os/failsafe/executor/utils/Database.java
> +import java.sql.*;
please revert and avoid `*` imports

2023-11-14 07:50 UTC, oliverselinger commented
Just had a look at the code. Couldn't this be resolved by passing a custom implementation of the SystemClock to the FailsafeExecutor constructor instead of the DefaultSystemClock which uses LocalDateTime provider?

The only timestamp that is not set by the system clock as far as I can see, is the creationTime. But this can also be set via SystemClock. So there wouldn't be a need for the TimeZone parameter.

2023-11-16 08:37 UTC, hokorn commented
> Just had a look at the code. Couldn't this be resolved by passing a custom implementation of the SystemClock to the FailsafeExecutor constructor instead of the DefaultSystemClock which uses LocalDateTime provider?
> 
> The only timestamp that is not set by the system clock as far as I can see, is the creationTime. But this can also be set via SystemClock. So there wouldn't be a need for the TimeZone parameter.

I will try

2023-11-16 12:54 UTC, hokorn commented on src/main/java/os/failsafe/executor/TaskRepository.java
> +import java.sql.*;
Fixed

2023-11-16 12:54 UTC, hokorn commented on src/main/java/os/failsafe/executor/FailsafeExecutor.java
> +import java.util.*;
Fixed

2023-12-05 08:10 UTC, closed without merging