Extend find all tasks filters
oliverselinger/failsafe-executor pull request #59
Opened 2024-05-15 12:18 UTC by AdrianSad

Goal of this MR is allowing the following filters:

- Parameter Id - text input
- 
- Failure date-time from / to
- 
- Created date-time from / to
- 
- Task Name - text input
- 
- Error Message contains text case insensitive (text input)

2024-05-27 15:20 UTC, oliverselinger requested changes

2024-05-28 12:37 UTC, AdrianSad commented on src/main/java/os/failsafe/executor/TaskRepository.java
> +    public List<Task> findAll(String taskName, String parameter, Boolean failed, String errorMessage, LocalDateTime createdDateFrom, LocalDateTime createdDateTo,
changed

2024-05-28 12:37 UTC, AdrianSad commented on src/main/java/os/failsafe/executor/TaskRepository.java
> +                .gt(getTimeString(createdDateFrom), "CREATED_DATE")
changed

2024-05-28 12:37 UTC, AdrianSad commented on src/main/java/os/failsafe/executor/TaskRepository.java
> +                .gt(getTimeString(failureDateFrom), "FAIL_TIME")
changed

2024-05-28 12:38 UTC, AdrianSad commented on src/main/java/os/failsafe/executor/TaskRepository.java
> +                .map(LocalDateTime::toString)
changed to `.map(Timestamp::valueOf)`

2024-05-28 17:36 UTC, oliverselinger approved these changes

2024-05-28 17:37 UTC, merged